version: '3.8'

services:
  my-python-app:
    image: python:3.7
    container_name: my-python-container
    volumes:
      - ./app:/app
    working_dir: /app
    command: python3 app.py
    ports:
      - "8000:8000"
